require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/proceedings', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Proceeding. As you add validations to Proceeding, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Proceeding.create! valid_attributes
      get proceedings_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      proceeding = Proceeding.create! valid_attributes
      get proceeding_url(proceeding)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_proceeding_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      proceeding = Proceeding.create! valid_attributes
      get edit_proceeding_url(proceeding)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Proceeding' do
        expect do
          post proceedings_url, params: { proceeding: valid_attributes }
        end.to change(Proceeding, :count).by(1)
      end

      it 'redirects to the created proceeding' do
        post proceedings_url, params: { proceeding: valid_attributes }
        expect(response).to redirect_to(proceeding_url(Proceeding.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Proceeding' do
        expect do
          post proceedings_url, params: { proceeding: invalid_attributes }
        end.to change(Proceeding, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post proceedings_url, params: { proceeding: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested proceeding' do
        proceeding = Proceeding.create! valid_attributes
        patch proceeding_url(proceeding), params: { proceeding: new_attributes }
        proceeding.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the proceeding' do
        proceeding = Proceeding.create! valid_attributes
        patch proceeding_url(proceeding), params: { proceeding: new_attributes }
        proceeding.reload
        expect(response).to redirect_to(proceeding_url(proceeding))
      end
    end

    context 'with invalid parameters' do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        proceeding = Proceeding.create! valid_attributes
        patch proceeding_url(proceeding), params: { proceeding: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested proceeding' do
      proceeding = Proceeding.create! valid_attributes
      expect do
        delete proceeding_url(proceeding)
      end.to change(Proceeding, :count).by(-1)
    end

    it 'redirects to the proceedings list' do
      proceeding = Proceeding.create! valid_attributes
      delete proceeding_url(proceeding)
      expect(response).to redirect_to(proceedings_url)
    end
  end
end
